'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { samplePublishedMacros } from '@/lib/published-macros/sample-data'
import { PublishedMacroReactions } from './PublishedMacroReactions'
// 最小項目だけを検索する。将来の本文検索・インデックス化は lib 側に分離する。
function matchesSearch(query: string, values: string[]) { return !query.trim() || values.join(' ').toLocaleLowerCase('ja-JP').includes(query.trim().toLocaleLowerCase('ja-JP')) }
export function PublishedMacroLibrary() {
 const [query, setQuery] = useState(''); const [activeTag, setActiveTag] = useState<string | null>(null); const tags = [...new Set(samplePublishedMacros.flatMap((macro) => macro.tags))]; const macros = useMemo(() => samplePublishedMacros.filter((macro) => (!activeTag || macro.tags.includes(activeTag)) && matchesSearch(query, [macro.title, macro.description, ...macro.tags])), [activeTag, query])
 return <main className="mx-auto w-full max-w-6xl px-6 py-12 sm:px-10"><section className="rounded-3xl bg-zinc-950 px-7 py-10 text-white shadow-xl sm:px-10"><p className="text-sm font-semibold tracking-[0.18em] text-amber-300">MACRO LIBRARY</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">公開マクロを探す</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-300">実用的なマクロを見つけ、エディタで自分用に調整できます。会話やプロフィールではなく、マクロそのものに集中するライブラリです。</p><Link href="/macros/submit" className="mt-6 inline-flex rounded-full bg-amber-300 px-5 py-2.5 text-sm font-bold text-zinc-950">共有 URL から公開する</Link></section><section className="mt-10"><label htmlFor="macro-search" className="block text-sm font-semibold">キーワードで探す</label><input id="macro-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="例：パーティ、採集、チャット" className="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-sm shadow-sm outline-none dark:border-zinc-700 dark:bg-zinc-900"/><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => setActiveTag(null)} className="rounded-full bg-zinc-900 px-3 py-1.5 text-sm font-medium text-white dark:bg-white dark:text-zinc-900">すべて</button>{tags.map((tag) => <button key={tag} type="button" onClick={() => setActiveTag(tag)} className="rounded-full bg-zinc-200 px-3 py-1.5 text-sm font-medium text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200">{tag}</button>)}</div></section><p className="mt-8 text-sm text-zinc-500">{macros.length} 件の公開マクロ</p><section className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{macros.map((macro) => <article key={macro.slug} className="flex min-h-72 flex-col rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="flex flex-wrap gap-2">{macro.tags.map((tag) => <span key={tag} className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-900 dark:bg-amber-300/15 dark:text-amber-200">{tag}</span>)}</div><h2 className="mt-4 text-lg font-semibold"><Link href={`/macros/${macro.slug}`} className="hover:underline">{macro.title}</Link></h2><p className="mt-2 text-sm leading-6 text-zinc-600 dark:text-zinc-300">{macro.description}</p><p className="mt-4 text-xs text-zinc-500">投稿者 {macro.authorHandle} · {macro.publishedAt}</p><div className="mt-auto pt-5"><PublishedMacroReactions macroSlug={macro.slug} initialHelpful={macro.reactions.helpful} initialProblem={macro.reactions.problem}/></div></article>)}</section>{macros.length === 0 && <p className="mt-3 rounded-2xl border border-dashed border-zinc-300 py-10 text-center text-sm text-zinc-500">条件に一致するマクロはありません。検索語やタグを変えてください。</p>}<p className="mt-10 rounded-xl bg-zinc-100 px-5 py-4 text-sm leading-6 text-zinc-600 dark:bg-zinc-900 dark:text-zinc-300">リアクションはログイン不要です。この試作ではブラウザの Cookie を使い、同じブラウザからは投稿ごとに一度だけ選べます。公開・集計の保存は次のバックエンド実装で追加します。</p></main>
}
